"""
actions: Utility module that provides functions for saving and loading numerical
matrices and exporting pandas DataFrames to disk. The goal of this module is to
standardize how results generated by the library are persisted and retrieved from
storage in a reproducible way.

Functions
1. ensure_parent_dir – Ensure the output directory exists before writing files.
2. save_matrix       – Save a NumPy matrix to disk in multiple supported formats.
3. load_matrix       – Load a matrix previously stored as NPY or NPZ.
4. save_dataframe    – Export pandas DataFrames in common formats.
5. _as_path          – Convert input path-like objects to Path.
6. _log_or_print     – Handle logging and optional console output.
"""

# ──────────────────────────────────────────────────────────────────────────────
# Libraries
# ──────────────────────────────────────────────────────────────────────────────
import logging
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, Optional, Union

import matplotlib
import numpy as np
import pandas as pd

# Use a headless backend so plotting operations remain safe in server environments.
matplotlib.use("Agg")

# Module-level logger used for status messages and error reporting.
logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# Enumerations
# ──────────────────────────────────────────────────────────────────────────────


class MatrixSaveMode(str, Enum):
    """
    Enumeration describing supported matrix storage formats.
    """

    BINARY_NPY = "npy"
    COMPRESSED_NPZ = "npz"
    TEXT_CSV = "csv"


class DataFrameFormat(str, Enum):
    """
    Enumeration describing supported DataFrame export formats.
    """

    CSV = "csv"
    EXCEL = "excel"
    PARQUET = "parquet"


@dataclass(frozen=True)
class MatrixSaveOptions:
    """
    Configuration options controlling how matrices are written to disk.

    Parameters
    ----------
    mode : MatrixSaveMode
        File format used for storing the matrix.

    delimiter : str
        Delimiter used when exporting text formats.

    fmt : str
        Numeric formatting string for text output.

    allow_pickle : bool
        Safety flag forwarded to NumPy loading operations.

    verbose : bool
        If True, additional messages may be printed.
    """

    mode: MatrixSaveMode = MatrixSaveMode.BINARY_NPY
    delimiter: str = ","
    fmt: str = "%.6f"
    allow_pickle: bool = False
    verbose: bool = False


# ──────────────────────────────────────────────────────────────────────────────
# Type definitions
# ──────────────────────────────────────────────────────────────────────────────
PathLike = Union[str, Path]


# ──────────────────────────────────────────────────────────────────────────────
# Internal helper functions
# ──────────────────────────────────────────────────────────────────────────────


def _as_path(path: PathLike) -> Path:
    """
    Convert a path-like input to a pathlib.Path object.

    Parameters
    ----------
    path : PathLike
        Input path represented as a string or Path.

    Returns
    -------
    Path
        Normalized Path object.
    """
    return path if isinstance(path, Path) else Path(path)


def _log_or_print(msg: str, verbose: bool = False) -> None:
    """
    Log a message and optionally print it.

    This helper keeps the module compatible with both logging systems
    and simple console-based workflows.

    Parameters
    ----------
    msg : str
        Message describing the performed action.

    verbose : bool
        If True, the message will also be printed.
    """

    logger.info(msg)

    if verbose:
        print(msg)


# ──────────────────────────────────────────────────────────────────────────────
# Public utility functions
# ──────────────────────────────────────────────────────────────────────────────


def ensure_parent_dir(filepath: PathLike) -> Path:
    """
    Ensure the parent directory of a file path exists.

    If the directory does not exist, it will be created automatically.

    Parameters
    ----------
    filepath : PathLike
        Path to the file that will be written.

    Returns
    -------
    Path
        Resolved Path object.
    """

    p = _as_path(filepath)
    parent = p.parent

    if parent and not parent.exists():
        parent.mkdir(parents=True, exist_ok=True)

    return p


def save_matrix(
    matrix: np.ndarray,
    filepath: PathLike,
    options: MatrixSaveOptions = MatrixSaveOptions(),
) -> Path:
    """
    Save a NumPy matrix to disk using different storage formats.

    Parameters
    ----------
    matrix : numpy.ndarray
        Matrix that will be written to disk.

    filepath : PathLike
        Output file path.

    options : MatrixSaveOptions
        Configuration describing the output format.

    Returns
    -------
    Path
        Path to the saved file.

    Raises
    -------
    TypeError
        If the provided matrix is not a NumPy array.

    ValueError
        If the save mode is unsupported.

    OSError
        If a file system error occurs during writing.
    """

    if not isinstance(matrix, np.ndarray):
        raise TypeError(f"`matrix` must be a numpy.ndarray, got: {type(matrix)}")

    p = ensure_parent_dir(filepath)

    desired_suffix = f".{options.mode.value}"

    if p.suffix.lower() != desired_suffix:
        p = p.with_suffix(desired_suffix)

    try:

        if options.mode == MatrixSaveMode.BINARY_NPY:
            np.save(p, matrix)
            _log_or_print(f"Matrix saved (NPY) at: {p}", options.verbose)

        elif options.mode == MatrixSaveMode.COMPRESSED_NPZ:
            np.savez_compressed(p, matrix=matrix)
            _log_or_print(f"Matrix saved (NPZ compressed) at: {p}", options.verbose)

        elif options.mode == MatrixSaveMode.TEXT_CSV:
            np.savetxt(p, matrix, delimiter=options.delimiter, fmt=options.fmt)
            _log_or_print(f"Matrix saved (text) at: {p}", options.verbose)

        else:
            raise ValueError(f"Unsupported mode: {options.mode}")

        return p

    except OSError:
        logger.exception("I/O error while saving matrix.")
        raise

    except Exception:
        logger.exception("Unexpected error while saving matrix.")
        raise


def load_matrix(
    filepath: PathLike,
    allow_pickle: bool = False,
    key: str = "matrix",
    display: bool = False,
    verbose: bool = False,
) -> np.ndarray:
    """
    Load a matrix stored as an NPY or NPZ file.

    Parameters
    ----------
    filepath : PathLike
        Path to the stored matrix file.

    allow_pickle : bool
        Safety flag forwarded to NumPy loader.

    key : str
        Key used when reading compressed NPZ archives.

    display : bool
        If True, prints the matrix after loading.

    verbose : bool
        If True, additional status messages are printed.

    Returns
    -------
    numpy.ndarray
        Loaded matrix.

    Raises
    -------
    FileNotFoundError
        If the matrix file cannot be found.

    KeyError
        If the requested key is not present inside an NPZ archive.
    """

    p = _as_path(filepath)

    candidates = [p] if p.suffix else [p.with_suffix(".npy"), p.with_suffix(".npz")]

    found: Optional[Path] = None

    for c in candidates:
        if c.exists():
            found = c
            break

    if found is None:
        raise FileNotFoundError(
            f"Matrix file not found. Tried: {', '.join(str(c) for c in candidates)}"
        )

    try:

        if found.suffix == ".npz":

            with np.load(found, allow_pickle=allow_pickle) as data:

                if key not in data.files:
                    raise KeyError(
                        f"Key '{key}' not found in NPZ file. Available: {data.files}"
                    )

                matrix = data[key]

        else:

            matrix = np.load(found, allow_pickle=allow_pickle)

        _log_or_print(f"Matrix loaded from: {found}", verbose)

        if display:
            print(matrix)

        return matrix

    except Exception:
        logger.exception("Error while loading matrix.")
        raise


def save_dataframe(
    dataframe: pd.DataFrame,
    filepath: PathLike,
    format: str = "csv",
    verbose: bool = False,
    **kwargs: Any,
) -> Path:
    """
    Save a pandas DataFrame using several common file formats.

    Parameters
    ----------
    dataframe : pandas.DataFrame
        DataFrame that will be exported.

    filepath : PathLike
        Output path.

    format : str
        Export format: csv, excel, or parquet.

    verbose : bool
        If True, prints status messages.

    **kwargs
        Additional parameters forwarded to pandas export functions.

    Returns
    -------
    Path
        Path to the created file.
    """

    if not isinstance(dataframe, pd.DataFrame):
        raise TypeError(
            f"`dataframe` must be a pandas.DataFrame, got: {type(dataframe)}"
        )

    fmt = format.lower().strip()

    try:
        df_format = DataFrameFormat(fmt)
    except ValueError as err:
        raise ValueError(
            "Unsupported format. Use 'csv', 'excel', or 'parquet'."
        ) from err

    p = ensure_parent_dir(filepath)

    if df_format == DataFrameFormat.CSV:

        if p.suffix.lower() != ".csv":
            p = p.with_suffix(".csv")

        dataframe.to_csv(p, index=False, **kwargs)
        _log_or_print(f"Results saved as CSV at: {p}", verbose)

    elif df_format == DataFrameFormat.EXCEL:

        if p.suffix.lower() not in (".xlsx", ".xls"):
            p = p.with_suffix(".xlsx")

        kwargs.setdefault("engine", "openpyxl")
        dataframe.to_excel(p, index=False, **kwargs)
        _log_or_print(f"Results saved as Excel at: {p}", verbose)

    elif df_format == DataFrameFormat.PARQUET:

        if p.suffix.lower() != ".parquet":
            p = p.with_suffix(".parquet")

        dataframe.to_parquet(p, index=False, **kwargs)
        _log_or_print(f"Results saved as Parquet at: {p}", verbose)

    return p
